[package]
name = "my_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
chrono = "0.4.23"


[target.'cfg(target_family="wasm")'.dependencies]
gloo-console = { version = "0.2.1" }
js-sys = "0.3.60"

[target.'cfg(target_family="wasm")'.dependencies.web-sys]
version = "0.3.4"
features = [
  'console'
]