[package]
name = "my_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
js-sys = "0.3.60"
chrono = "0.4.23"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console'
]