[package]
name = "yew-nani"
version.workspace = true
edition = "2021"

[dependencies]
cdec = { path = "../cdec" }
ecco = { path = "../ecco" }
log = "=0.4.18"
my_log = { path = "../my_log" }
wasm-bindgen = "=0.2.86"
yew = { version = "=0.20.0", features = ["csr"] }


[dependencies.web-sys]
version = "=0.3.63"
features = [
  'Document',
  'HtmlSelectElement',
  'Window',
  'console'
]
