[package]
name = "yew-nani"
version.workspace = true
edition = "2021"

[dependencies]
cdec = { path = "../cdec" }
ecco = { path = "../ecco" }
chrono = { version = "0.4.22", features = ["serde"] }
js-sys = "0.3.60"
log = "0.4.17"
my_log = { path = "../my_log" }
wasm-bindgen = "0.2.83"
yew = { version = "0.20.0", features = ["csr"] }


[dependencies.web-sys]
version = "0.3.60"
features = [
  'Document',
  'HtmlSelectElement',
  'Window',
  'console'
]
