[package]
name = "yew-nani"
version = "0.1.0"
edition = "2021"

[dependencies]
cdec = { path = "../cdec" }
ecco = { path = "../ecco" }
gloo-console = { version = "0.2.1" }
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"
yew = { version = "0.20.0", features = ["csr"] }


[dependencies.web-sys]
version = "0.3.60"
features = [
  'Document',
  'HtmlSelectElement',
  'Window',
  'console'
]