[package]
name = "yew-wot_m8"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdec = { path = "../cdec" }
chrono = { version = "0.4.31", features = ["serde"] }
ecco = { path = "../ecco" }
log = "0.4.20"
my_log = { path = "../my_log" }
plotters = "0.3.5"
wasm-bindgen = "0.2.87"
yew = { version = "0.21.0", features = ["csr"]}

[dependencies.web-sys]
version = "0.3.64"
features = [
  'Document',
  'Element',
  'HtmlSelectElement',
  'Window',
  'console'
]
