[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
chrono = { version = "0.4.22", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
csv = "1.1.6"
futures = "0.3.25"
cdec = { path = "../cdec" }
tokio = { version = "1", features = ["full", "tracing"] }
reqwest = "0.11.12"
log = "0.4.17"