[package]
name = "cli"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmd = {path = "../cmd"}
clap = { version = "4.0.18", features = ["derive"] }
log = "0.4.17"
my_log = {path = "../my_log"}
tokio = { version = "1", features = ["full", "tracing"] }
utils = {path = "../utils"}