[package]
name = "cli"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdec = { path = "../cdec" }
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "4.0.18", features = ["derive"] }
csv = "1.1.6"
easy-cast = "0.5.1"
futures = "0.3.25"
log = "0.4.17"
reqwest = "0.11.12"
tokio = { version = "1", features = ["full", "tracing"] }