[package]
name = "yew-wu"
version.workspace = true
edition = "2021"

[[bin]]
name="uwu"
path="src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
easy-cast = "0.5.1"
ecco = { path = "../ecco" }
js-sys = "0.3.60"
log = "0.4.17"
my_log = { path = "../my_log" }
plotters = "0.3.4"
wasm-bindgen = "0.2.83"
yew = { version = "0.20.0", features = ["csr"] }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlInputElement',
  'Window',
  'console'
]
