[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdec = {path= "../cdec"}
chrono = "0.4.23"
clap = { version = "4.0.18", features = ["derive"] }
csv = "1.1.6"
easy-cast = "0.5.1"
ecco = { path="../ecco" }
futures = "0.3.25"
log = "0.4.17"
my_log = {path = "../my_log"}
reqwest = "0.11.12"
tokio = { version = "1", features = ["full", "tracing"] }
utils = {path="../utils"}
