[package]
name = "cmd"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdec = {path= "../cdec"}
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
csv = "1.3.0"
easy-cast = "0.5.2"
futures = "0.3.28"
log = "0.4.20"
reqwest = "0.11.22"
utils = {path="../utils"}
