[package]
name = "cmd"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdec = {path= "../cdec"}
chrono = "0.4.24"
clap = { version = "4.2.5", features = ["derive"] }
csv = "1.2.1"
easy-cast = "0.5.2"
futures = "0.3.28"
log = "0.4.17"
reqwest = "0.11.17"
utils = {path="../utils"}
