[package]
name = "ecco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdec = { path = "../cdec" }
chrono = { version = "0.4.22", features = ["serde"] }
easy-cast = "0.5.1"
gloo-console = { version = "0.2.1" }
itertools = "0.10.5"
js-sys = "0.3.60"
modpow = "1.0.1"
num-bigint = "0.4.3"
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2.83"
yew = "0.19"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'HtmlInputElement',
  'Window',
  'console'
]